mblog/urls.py
from django.contrib import admin
from django.urls import path, include
from Handwriting_recognition.views import *
from mainsite.views import homepage, showpost
from django.conf.urls.static import static

from django.conf import settings
# from . import views

urlpatterns = [
    # path('', include('Handwriting_recognition.urls')),
    path('admin/', admin.site.urls),
    path('upload/', image_upload_method),
    path('post/<slug:slug>', showpost),
    path('',homepage),
    path('index/', index),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Handwriting_recognition/models.py
# from django.db import models

# # Create your models here.
from pyexpat import model
from turtle import title
from django.db import models

# Create your models here.
class upload_img(models.Model):
    請輸入員工編號 = models.CharField(max_length=200)
    選擇檔案 = models.ImageField(upload_to="static/upload_img")

templates/base.html
<!-- base.html -->
<html>
<head>
    {% include 'header.html' %}
    <title>
        {% block title %} 
        
        {% endblock %}
    </title>

    {% load static %}

</head>
<body>
{% comment %} 修改內容 {% endcomment %}
    <div class='container-fluid'>
        <div class="well post_title">
            <h1><img width="100" height="100" src="{% static 'img/logo.gif' %}">文齋</h1>
            <img width="100" height="100" src="../static/img/logo.jpg">
        </div>
        <div class='panel panel-default'>
            <div class="row">
                {% include 'menu.html' %}
                <div class='col-sm-8 col-md-8'>
                    <div class="panel-header">
                        {% block headmessage %} {% endblock %}
                    </div>
                    <div class="panel-body">
                        {% block content %} {% endblock %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel-footer">
                    {% include 'footer.html' %}
                </div>
            </div>
        </div>
    </div>
{% comment %} 修改內容 {% endcomment %}

</body>
</html>

templates/footer.html
<!-- footer.html -->
{% block footer %}
    {% if now %}
    <p style='font-family:微軟正黑體;'>現在時刻：{{ now }}</p>
    {% else %}
    <p style='font-family:微軟正黑體;'>本文內容取自網路，如有侵權請來信通知下架...</p>
    {% endif %}
{% endblock %}

templates/header.html
<meta charset='utf-8'>

<title>
    文齋
</title>
<style>
    .post_title {
        font-family: 微軟正黑體;
        font-size: 16pt;
        font-weight: bold;
    }
    
    .post_body {
        font-family: 微軟正黑體;
        font-size: 10pt;
        letter-spacing: 1pt;
        background-color: #ffffdd;
    }
    .post_date {
        background-color: #efefef;
    }
    .inline-headers h1 {
        display: inline-block;
        vertical-align: baseline;
    }
</style>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

templates/index.html
<!-- index.html -->
{% extends 'base.html' %}

{% block title %} 
歡迎光臨我的部落格 
{% endblock %}

{% block headmessage %} 
    <h3 style='font-family:標楷體;'>本站文章列表</a>
{% endblock %}


{% block content %} 

    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
            <div class='post_title'>
                <a href='/post/{{post.slug}}'>{{post.title}}</a>
            </div>
            </div>
            <div class="panel-body">
                {{post.body | safe | truncatewords_html:'120' }}
            </div>
            <div class="panel-footer">
                {{post.pub_date | date:"Y-m-d H:m:s"}}
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

templates/index_hand.html
<h1>Handwriting_recognition App</h1>
{% comment %} <p>A simple Django web app with a pretrained PyTorch DenseNet model will try to classify the selected image according to ImageNet labels. Uploaded images are not saved.</p> {% endcomment %}
{% comment %} <p><small>Further information:
    <a href="" target="_blank">Blog Post</a>,
    <a href="https://github.com/stefanbschneider/pytorch-django" target="_blank">GitHub</a></small>
</p> {% endcomment %}

<form method="post" enctype="multipart/form-data" style="margin-top: 50px; margin-bottom: 30px;">
    {% csrf_token %}
    {{ form }}
    <button type="submit" id="btnUpload" class="btn btn-primary">Upload</button>
</form>

{% if image_uri is not None %}
    {% if predicted_label is not None %}
        <div class="alert alert-primary" role="alert">
            此簽名為: <b>{{ predicted_label }}</b>
        </div>
    {% else %}
        <div class="alert alert-danger" role="alert">
            Prediction error. No label predicted.
        </div>
    {% endif %}

    <img src="{{ image_uri }}" class="img-fluid" alt="Uploaded image"
         style="max-width: min(500px, 100%); height: auto; margin-top: 30px;">
{% endif %}

templates/menu.html
<div class='col-sm-4 col-md-4'>
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <h3>	
                MENU
            </h3>
        </div>
        <div class='panel-body'>
            <div class='list-group'>
                <a href='/' class='list-group-item'>HOME</a>
                <a href='/admin' class='list-group-item'>管理頁面</a>
                <a href='#' class='list-group-item'>預備連結</a>
                <a href='index/' class='list-group-item'>字跡辨識</a>
                {% comment %} <a href='sign/' class='list-group-item'>簽到頁面</a> {% endcomment %}
            </div>                
        </div>

        <a href="http://guestscounter.com"><img src="http://guestscounter.com/count.php?c_style=26&id=1626663560" border=0 alt="free hit counter"></a><br><a href="http://guestscounter.com" style="font-size:9px;">free hit counter</a><br>
        <script id="_waurg4">var _wau = _wau || []; _wau.push(["map", "3mg7nl9zh5", "rg4", "250", "125", "night", "cross-pink"]);</script><script async src="//waust.at/m.js"></script>
        <script id="_waufwe">var _wau = _wau || []; _wau.push(["classic", "468y1ph1wd", "fwe"]);</script><script async src="//waust.at/c.js"></script>
        <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button_count&size=small&width=100&height=20&appId" width="100" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
        <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fwww.facebook.com%2F888papa&layout=button_count&size=small&width=84&height=20&appId" width="84" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
    </div>
</div>

templates/post.html
<!-- post.html -->
{% extends 'base.html' %}
{% block title %} {{ post.title }} - 文學天地 {% endblock %}
{% block headmessage %}
    <div class='post_title'>
        <h3>{{ post.title }}</h3>
        <a style='font-family:微軟正黑體;' href='/'>回首頁</a>
    </div>
{% endblock %}
{% block content %} 
        <div class='post_body'>
            {{ post.body }}</a>
        </div>
{% endblock %}

templates/sign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>UCCU Tech 出勤打卡系統</title>
    <meta name="viewport" content="width=device-width, initial-scale=2.0">
    <style type="text/css">
    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, fieldset, input, textarea, p, blockquote, th, td {
	    margin:0;
	    padding:0;
    }
    table {
	    border-collapse:collapse;
	    border-spacing:100;
    }
    fieldset, img {
	    border:0;
    }
    address, caption, cite, code, dfn, em, strong, th, var {
	    font-style:normal;
	    font-weight:normal;
    }
    ol, ul {
	    list-style:none;
    }
    caption, th {
	    text-align:left;
    }

    q:before, q:after {
	    content:'';
    }
    abbr, acronym {
	    border:0;
    }

    nav{
	    background-color: #d1d1d1;
	    width: 100%;
	    height: 5vw;
	    position: relative;


    }
    nav ul{
	    position: absolute;
	    top: 0vw;
	    left: 60vw;
    }

    nav ul li{
	    float: left;
    }

    nav ul li a{
	    text-align: center;
	    text-decoration: none;
	    display: block;
	    font-size: 1vw;
	    width: 8vw;
	    line-height: 5vw;
	    color: black;
	    letter-spacing: 2px;
    }
    nav ul li a:hover{
    	color: #F29600;
    }
    #LOGO{
    	font-size: 1vw;
	    width: 5vw;
	    height: 5vw;
	    text-align: center;
	    line-height: 5vw;
	    background-color: white;
	    position: absolute;
	    left: 5vw;
    }

    main{
    	background-color: #fdeee9;
	    padding-bottom: 2vw
    }
    main h1{
    	margin-left: 2vw;
	    font-size: 4vw;
    	line-height:7vw; 
    }
    main h3{
	    text-align: center;
    	font-size: 3vw;
	    line-height: 6vw;
    }
    #CHECK{
	    width: 50%;
	    margin-left: 25%;
	    padding-bottom: 2vw;
    }
    #CHECK input{
	    margin-top: 0.5vw;
    }
    input[type="submit"]{
     	width: 20vw;
    }
    input[type="Reset"]{
     	width: 20vw;
    }
    #BOX{
    	width: 50%;
	    margin-left: 25%;
	    background-color: #ffffff;
	    border: 1px solid black;
	    text-align: center;
	    padding-bottom: 1vw;
    }
    #BOX p {
	    font-size: 4vw;
	    line-height: 8vw;
    }
    #UPLOAD{
	    width: 50%;
	    margin-left: 25%;
    }
    footer{
	    background-color: #d1d1d1;
	    text-align: center;
	    padding-top: 4vw;
    }

    </style>
</head>
    <body>
        <div>
            <nav>
              <div id="LOGO">UCCU</div>
                <ul>
		        <li><a href="TBC.html">首頁</a></li>
		        <li><a href="TBC.html">出勤紀錄</a></li>
		        <li><a href="TBC.html">操作方式</a></li>
		        <li><a href="TBC.html">製作團隊</a></li>
                </ul>
            </nav>
            <main>
                <h3>UCCU Tech 出勤打卡系統</h3>
                <script language="JavaScript">
                    function ShowTime(){
                    　var NowDate=new Date();
                    　var year=NowDate.getFullYear();
                    　var month=NowDate.getMonth();
                    　var day=NowDate.getDate();
                    　var h=NowDate.getHours();
                    　var m=NowDate.getMinutes();
                    　var s=NowDate.getSeconds();　
                    　document.getElementById('showbox').innerHTML =year+'年'+month+'月'+day+'日'+'   '+h+'時'+m+'分'+s+'秒';
                    　setTimeout('ShowTime()',1000);
                    }
                </script>
                <body onload="ShowTime()">
    
                <h3><div id="showbox"></div></h3>
                <div id="CHECK">
                    <input style="width: 100%; height: 4vw; text-align: center;" value="請輸入員工編號"><br>
                </div>
                <div id="BOX">
                    <p>請簽名</p>
                    <div id="UPLOAD">
                        <input type="file" accept="image/*,.pdf"><br>
                    </div>
                </div>
                <div id="BUTTOM">
                    <input style="margin-right: 5vw; margin-left: 27vw;" type="submit" value="確認">
                    <input type="reset" value="清除">
                </div>
            </main>
            <footer>
                <p>COPYRIGHT © UCCU</p>	
            </footer>
        </div>
    </body>
</html>

templates/upload_ui.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>UCCU Tech 出勤打卡系統</title>
    <meta name="viewport" content="width=device-width, initial-scale=2.0">
    <style type="text/css">
    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, fieldset, input, textarea, p, blockquote, th, td {
	    margin:0;
	    padding:0;
    }
    table {
	    border-collapse:collapse;
	    border-spacing:100;
    }
    fieldset, img {
	    border:0;
    }
    address, caption, cite, code, dfn, em, strong, th, var {
	    font-style:normal;
	    font-weight:normal;
    }
    ol, ul {
	    list-style:none;
    }
    caption, th {
	    text-align:left;
    }

    q:before, q:after {
	    content:'';
    }
    abbr, acronym {
	    border:0;
    }

    nav{
	    background-color: #d1d1d1;
	    width: 100%;
	    height: 5vw;
	    position: relative;


    }
    nav ul{
	    position: absolute;
	    top: 0vw;
	    left: 60vw;
    }

    nav ul li{
	    float: left;
    }

    nav ul li a{
	    text-align: center;
	    text-decoration: none;
	    display: block;
	    font-size: 1vw;
	    width: 8vw;
	    line-height: 5vw;
	    color: black;
	    letter-spacing: 2px;
    }
    nav ul li a:hover{
    	color: #F29600;
    }
    #LOGO{
    	font-size: 1vw;
	    width: 5vw;
	    height: 5vw;
	    text-align: center;
	    line-height: 5vw;
	    background-color: white;
	    position: absolute;
	    left: 5vw;
    }

    main{
    	background-color: #fdeee9;
	    padding-bottom: 2vw
    }
    main h1{
    	margin-left: 2vw;
	    font-size: 4vw;
    	line-height:7vw; 
    }
    main h3{
	    text-align: center;
    	font-size: 3vw;
	    line-height: 6vw;
    }
    #CHECK{
	    width: 50%;
	    margin-left: 25%;
	    padding-bottom: 2vw;
    }
    #CHECK input{
	    margin-top: 0.5vw;
    }
    input[type="submit"]{
     	width: 20vw;
    }
    input[type="Reset"]{
     	width: 20vw;
    }
    #BOX{
    	width: 50%;
	    margin-left: 25%;
	    background-color: #ffffff;
	    border: 1px solid black;
	    text-align: center;
	    padding-bottom: 1vw;
    }
    #BOX p {
	    font-size: 4vw;
	    line-height: 8vw;
    }
    #UPLOAD{
	    width: 50%;
	    margin-left: 25%;
    }
    footer{
	    background-color: #d1d1d1;
	    text-align: center;
	    padding-top: 4vw;
    }

    </style>
</head>
    <body>
        <div>
            <nav>
              <div id="LOGO">UCCU</div>
                <ul>
		        <li><a href="TBC.html">首頁</a></li>
		        <li><a href="TBC.html">出勤紀錄</a></li>
		        <li><a href="TBC.html">操作方式</a></li>
		        <li><a href="TBC.html">製作團隊</a></li>
                </ul>
            </nav>
            <main>
                <h3>UCCU Tech 出勤打卡系統</h3>
                <script language="JavaScript">
                    function ShowTime(){
                    　var NowDate=new Date();
                    　var year=NowDate.getFullYear();
                    　var month=NowDate.getMonth() + 1;
                    　var day=NowDate.getDate();
                    　var h=NowDate.getHours();
                    　var m=NowDate.getMinutes();
                    　var s=NowDate.getSeconds();　
                    　document.getElementById('showbox').innerHTML =year+'年'+month+'月'+day+'日'+'   '+h+'時'+m+'分'+s+'秒';
                    　setTimeout('ShowTime()',1000);
                    }
                </script>
                <body onload="ShowTime()">
    
                <h3><div id="showbox"></div></h3>
                <div id="BOX">
                    {% comment %} context = {
                        'form': form,
                        'image_uri': image_uri,
                        'predicted_label': predicted_label,
                    } {% endcomment %}
                    {% comment %} <p> {{ image_uri }}</p>
                    <p> {{ predicted_label }}</p> {% endcomment %}
                    <form enctype="multipart/form-data" id="id_ajax_upload_form" method="POST" novalidate="">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" />
                        <br>
                        <img id="upload_img" src="" />
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                        <script type="text/javascript">
                         // form upload
                         $('#id_ajax_upload_form').submit(function(e){
                             e.preventDefault();
                             $form = $(this)
                             var formData = new FormData(this);
                             $.ajax({
                                 url: window.location.pathname,
                                 type: 'POST',
                                 data: formData,
                                 success: function (response) {
                                     $('.error').remove();
                                     console.log(response)
                                     if(response.error){
                                         $.each(response.errors, function(name, error){
                                             error = '<small class="text-muted error">' + error + '</small>'
                                             $form.find('[name=' + name + ']').after(error);
                                         })
                                     }
                                     else{
                                         alert(response.message)
                                         window.location = ""
                                     }
                                 },
                                 cache: false,
                                 contentType: false,
                                 processData: false
                             });
                         });
                         // end
                         $('#id_選擇檔案').on('change', function(e){      
                            const file = this.files[0];//將上傳檔案轉換為base64字串
                                
                            const fr = new FileReader();//建立FileReader物件
                            fr.onload = function (e) {
                               upload_img=$('#upload_img');
                               upload_img.attr('src', e.target.result);//读取的结果放入圖片
                               //upload_img.attr('width', 500);//設定寬度
                               //upload_img.attr('height', 500);//設定寬度
                        };
                          
                      // 使用 readAsDataURL 將圖片轉成 Base64
                        fr.readAsDataURL(file);
                     });
                        </script>
                     </form>
                </div>
            </main>
            <footer>
                <p>COPYRIGHT © UCCU</p>	
            </footer>
        </div>
    </body>
</html>

templates/upload_ui_榮昇.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>UCCU Tech 出勤打卡系統</title>
    <meta name="viewport" content="width=device-width, initial-scale=2.0">
    <style type="text/css">
    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, fieldset, input, textarea, p, blockquote, th, td {
	    margin:0;
	    padding:0;
    }
    table {
	    border-collapse:collapse;
	    border-spacing:100;
    }
    fieldset, img {
	    border:0;
    }
    address, caption, cite, code, dfn, em, strong, th, var {
	    font-style:normal;
	    font-weight:normal;
    }
    ol, ul {
	    list-style:none;
    }
    caption, th {
	    text-align:left;
    }

    q:before, q:after {
	    content:'';
    }
    abbr, acronym {
	    border:0;
    }

    nav{
	    background-color: #d1d1d1;
	    width: 100%;
	    height: 5vw;
	    position: relative;


    }
    nav ul{
	    position: absolute;
	    top: 0vw;
	    left: 60vw;
    }

    nav ul li{
	    float: left;
    }

    nav ul li a{
	    text-align: center;
	    text-decoration: none;
	    display: block;
	    font-size: 1vw;
	    width: 8vw;
	    line-height: 5vw;
	    color: black;
	    letter-spacing: 2px;
    }
    nav ul li a:hover{
    	color: #F29600;
    }
    #LOGO{
    	font-size: 1vw;
	    width: 5vw;
	    height: 5vw;
	    text-align: center;
	    line-height: 5vw;
	    background-color: #FFF7E8;
	    position: absolute;
	    left: 0vw;
    }

    main{
    	background-color: #fdeee9;
	    padding-bottom: 2vw
    }
    main h1{
    	margin-left: 2vw;
	    font-size: 4vw;
    	line-height:7vw; 
    }
    main h3{
	    text-align: center;
    	font-size: 3vw;
	    line-height: 6vw;
    }
    #CHECK{
	    width: 50%;
	    margin-left: 25%;
	    padding-bottom: 2vw;
    }
    #CHECK input{
	    margin-top: 0.5vw;
    }
    input[type="submit"]{
     	width: 30vw;
    }
    input[type="Reset"]{
     	width: 20vw;
    }
    #BOX{
    	width: 40%;
	    margin-left: 30%;
	    background-color: #F5F5F5;
	    border: 1px solid black;
	    text-align: center;
	    padding-bottom: 1vw;
    }
    #BOX p {
	    font-size: 2vw;
	    line-height: 6vw;
    }
    #UPLOAD{
	    width: 50%;
	    margin-left: 25%;
    }
    footer{
	    background-color: #d1d1d1;
	    text-align: center;
	    padding-top: 4vw;
    }

    </style>
</head>
    <body>
        <div>
            <nav>
              <div id="LOGO">UCCU</div>
                <ul>
		        <li><a href="TBC.html">首頁</a></li>
		        <li><a href="TBC.html">出勤紀錄</a></li>
		        <li><a href="TBC.html">操作方式</a></li>
		        <li><a href="TBC.html">製作團隊</a></li>
                </ul>
            </nav>
            <main>
                <h3>UCCU Tech 出勤打卡系統</h3>
                <script language="JavaScript">
                    function ShowTime(){
                    　var NowDate=new Date();
                    　var year=NowDate.getFullYear();
                    　var month=NowDate.getMonth();
                    　var day=NowDate.getDate();
                    　var h=NowDate.getHours();
                    　var m=NowDate.getMinutes();
                    　var s=NowDate.getSeconds();　
                    　document.getElementById('showbox').innerHTML =year+'年'+month+'月'+day+'日'+'   '+h+'時'+m+'分'+s+'秒';
                    　setTimeout('ShowTime()',1000);
                    }
                </script>
                <body onload="ShowTime()">
    
                <h3><div id="showbox"></div></h3>
                <div id="BOX">
                    {% comment %} context = {
                        'form': form,
                        'image_uri': image_uri,
                        'predicted_label': predicted_label,
                    } {% endcomment %}
                    {% comment %} <p> {{ image_uri }}</p>
                    <p> {{ predicted_label }}</p> {% endcomment %}
                    <form enctype="multipart/form-data" id="id_ajax_upload_form" method="POST" novalidate="">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" />
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                        <script type="text/javascript">
                         // form upload
                         $('#id_ajax_upload_form').submit(function(e){
                             e.preventDefault();
                             $form = $(this)
                             var formData = new FormData(this);
                             $.ajax({
                                 url: window.location.pathname,
                                 type: 'POST',
                                 data: formData,
                                 success: function (response) {
                                     $('.error').remove();
                                     console.log(response)
                                     if(response.error){
                                         $.each(response.errors, function(name, error){
                                             error = '<small class="text-muted error">' + error + '</small>'
                                             $form.find('[name=' + name + ']').after(error);
                                         })
                                     }
                                     else{
                                         alert(response.message)
                                         window.location = ""
                                     }
                                 },
                                 cache: false,
                                 contentType: false,
                                 processData: false
                             });
                         });
                         // end
                         $('#id_選擇檔案').on('change', function(e){      
                            const file = this.files[0];//將上傳檔案轉換為base64字串
                                
                            const fr = new FileReader();//建立FileReader物件
                            fr.onload = function (e) {
                               upload_img=$('#upload_img');
                               upload_img.attr('src', e.target.result);//读取的结果放入圖片
                               //upload_img.attr('width', 500);//設定寬度
                               //upload_img.attr('height', 500);//設定寬度
                        };
                          
                      // 使用 readAsDataURL 將圖片轉成 Base64
                        fr.readAsDataURL(file);
                    });
                        </script>
                     </form>
                </div>
            </main>
            <footer>
                <p>COPYRIGHT © UCCU</p>	
            </footer>
        </div>
    </body>
</html>